[project]
name = "llama-stack-setup"
version = "0.1.0"
description = "Runs llama stack for this demo"
requires-python = ">=3.12"
dependencies = [
    "greenlet>=3.2.4",
    "litellm>=1.76.3",
    "llama-stack>=0.2.20",
    "mcp>=1.13.1",
    "sqlalchemy>=2.0.43",
]
