---
apiVersion: v1
kind: Namespace
metadata:
  name: demo-auth
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-pod-reader
  namespace: demo-auth
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-pod-reader
  namespace: demo-auth
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rb-pod-reader
  namespace: demo-auth
subjects:
  - kind: ServiceAccount
    name: sa-pod-reader
    namespace: demo-auth
roleRef:
  kind: Role
  name: role-pod-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-reader-test
  namespace: demo-auth
spec:
  serviceAccountName: sa-pod-reader
  containers:
    - name: tester
      image: bitnami/kubectl:1.30.0   # small image with kubectl installed
      command: ["sleep", "infinity"]